app:
  telegramToken: "6587966045:AAE9qMrXldqYXuPI44LeYbq61o3aQl6MsTQ"
  botName: myfirst686868bot
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
